config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get 'homes/index'
  get 'users/new'
  devise_for :users, controllers: { registrations: 'users/registrations' }
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
   get 'users/show'
   get 'users/edit'
   

  resources :users do
  end
   
  resources :rooms do
    member do
      get 'own'
    end
  end

  resources :reservations do
    member do
      post 'confirm'
      get 'confirm'
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @user = current_user
  end

   def show
   @user = current_user
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<main>
<section class="FirstView">
<img class="FirstView__main-image">
<h1 class="FirstViewTitle">
  Potepan Shareで<br>
  まだ体験したことのない<br>
  旅をしよう
</h1>

<div class="firstview">
    <section class="main-container">
        <div class="FirstViewSearch">
            <%= search_form_for @q do |f| %>
                <div class="SearchnForm__input">
                <%= f.search_field :address_cont , placeholder: 'エリア名を入力', class:"form-control FirstViewSearch__input"  %>
                </div>
                <%= f.submit :検索 ,class:"btn FirstViewSearch__button"%>
            <% end %>
        </div>
        </div>
    </section>
</div>
<section class="area">
  <h2 class="Recommend_title">
    おすすめのエリア
  </h2>

  <div class="RecommendAreas">

    <%= link_to rooms_path(q: {address_cont: "東京"}),class:"RecommendArea RecommendArea--tokyo" do %>
      <span class="RecommendArea__name RecommendArea__name--ja">東京</span>
        <span class="RecommendArea__name RecommendArea__name--en">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
          <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
        </svg>
         Tokyo
      </span>
  <%end%>

     <%= link_to rooms_path(q: {address_cont: "大阪"}) ,class:"RecommendArea RecommendArea--osaka" do%>
        <span class="RecommendArea__name RecommendArea__name--ja">大阪</span>
        <span class="RecommendArea__name RecommendArea__name--en">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
            <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
          </svg>
          Osaka
        </span>
    <%end%>

    <%= link_to rooms_path(q: {address_cont: "京都"}) ,class:"RecommendArea RecommendArea--kyoto" do%>
        <span class="RecommendArea__name RecommendArea__name--ja">京都</span>
        <span class="RecommendArea__name RecommendArea__name--en">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
            <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
          </svg>
          Kyoto
        </span>
     <%end%>  

        <%= link_to rooms_path(q: {address_cont: "札幌"}) ,class:"RecommendArea RecommendArea--sapporo" do%>
          <span class="RecommendArea__name RecommendArea__name--ja">札幌</span>
          <span class="RecommendArea__name RecommendArea__name--en">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"></path>
            </svg>
            Sapopro
          </span>
      <%end%>
  </div>
</section>
</div>
        


    
    
    
    
    