config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get 'homes/index'
  get 'users/new'
  devise_for :users, controllers: { registrations: 'users/registrations' }
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
   get 'users/show'
   get 'users/edit'
   

  resources :users do
  end
   
  resources :rooms do
    member do
      get 'own'
    end
  end

  resources :reservations do
    member do
      post 'confirm'
      get 'confirm'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations, dependent: :destroy

    validates :name,:introduction,:address, presence: true
    validates :price , numericality: { greater_than_or_equal_to: 1 }
  

    mount_uploader :image, ImageUploader
  

    def self.ransackable_attributes(auth_object = nil)
      ["address", "name","introduction"]
  end

  #よくわからないけど必要
  def self.ransackable_associations(auth_object = nil)
      ["user"]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @user = current_user
  end

  def new
    @room = Room.new
    @user = current_user
   end

   def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id 
      if @room.save
        flash[:notice] = "新規登録しました"
        redirect_to @room
      else
        flash.now[:alert] = "登録に失敗しました"
        render "new"
      end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end


  def edit
    @room = Room.find(params[:id])
    @user = current_user
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "宿泊施設を更新しました"
      redirect_to @room
    else
      flash.now[:alert] = "宿泊施設の更新に失敗しました"
      render :edit , status: :unprocessable_entity
    end
  end

  def destroy
    @user = current_user
    @room = Room.find(params[:id])
    @room.destroy
      flash[:notice] = "ユーザーを削除しました"
      redirect_back(fallback_location: root_path)
  end

  def own
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end



  private
    def room_params
      params.require(:room).permit(
        :image,
        :name,
        :introduction,
        :price,
        :address,
        :user_id,
      )
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="main-container">
  <section class="FormContainer">
    <h2>施設情報の編集</h2>

    <%= render "shared/error", obj: @room %>

  <%= form_with model: @room do |f| %>
  <div class="form">
    <%= f.label :name ,"施設名" %>
    <div class="form_btn">
      <%= f.text_field :name ,class:"form-control" ,id:"name",placeholder:"ルーム名を入力",  size: 50 %>
    </div>
   <div class="form_btn">
     <%= f.label :introduction,"施設詳細" %>
    <div class="form_btn">
      <%= f.text_area :introduction ,class:"form-control" ,id:"introduction",placeholder:"施設詳細を入力", size: "50x5"  %>
    </div>
   <div class="form_btn">
     <%= f.label :price ,"料金" %>
     <div class="form_btn">
      <%= f.number_field :price ,class:"form-control" ,id:"price",placeholder:"料金を入力", size: 50 %>
    </div>
   <div class="form_btn">
     <%= f.label :address, "住所" %>
     <div class="form_btn">
      <%= f.text_field :address ,class:"form-control" ,id:"address",placeholder:"住所を入力",  size: 50 %>
    </div>

  <div class="iamge_form">
    <%= f.label :image, "施設画像" %>
    <%= f.file_field :image,class:"form-control" ,id:"image"%>

    <div class="form_btn">
    <%= f.submit "保存" ,class:"btn"%>
    </div>
  </section>
<% end %>
</div>

app/views/rooms/index.html.erb
<div class="SearchRoomsFormContainer">
    <%= search_form_for(@q, html: {class:"SearchRoomsForm"} )do |f| %>
        <div class="SearchRoomsForm__input-group SearchRoomsForm__input-group--area">
            <%= f.search_field :address_cont , placeholder: 'エリア名' , class:"form-control SearchRoomsForm__input"%>
        </div>

        <div class="SearchRoomsForm__input-group SearchRoomsForm__input-group--keyword">
            <%= f.search_field :introduction_or_name_cont , placeholder: 'キーワード名を入力' , class:"form-control SearchRoomsForm__input"%>
        </div>

        <%= f.submit:検索 ,class:"SearchRoomsForm__button" %>
    <% end %>
</div>
<div class="container RoomsContainer">
    <p class="RoomsContainer__result"><%= "#{@rooms.count}件が見つかりました。" %></p>

    <ul class="RoomList ">
        <% @rooms.each do |room| %>
            <li class="Room">
            <% if  room.image?%>
            <%= image_tag room.image.url , class: "image", style: "width: 100px; height: 100px; object-fit:cover;"%>
          <% else %>
            <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "image", style: "width: 100px; height: 100px; object-fit:cover;" %></p>
          <% end %>
            
            
            <p class="Room__name"><%= room.name %></p>

                    <p class="Room__address"><%= room.address %></p>

                    <p class="Room__content"><%= room.introduction %></p>

                    <div class="RoomFooter">
                        <p class="Room__price">¥<%= room.price %>~</p>
                        <%=link_to "詳細はこちら", room_path(room.id) ,class:"Room__link"%>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
</div>

app/views/rooms/new.html.erb
<div class="main-container">
    <section class="FormContainer">
        <h2>施設登録</h2>

    <%= render "shared/error", obj: @room %>

    <%= form_with model: @room do |f| %>
    <div class="form">
    <%= f.label :name ,"施設名" %>
    <div class="form_btn">
    <%= f.text_field :name ,class:"form-control" ,id:"name",placeholder:"ルーム名を入力",  size: 50 %>
    </div>

    <div class="form_btn">
    <%= f.label :introduction,"施設詳細" %>
    <div class="form_btn">
    <%= f.text_area :introduction ,class:"form-control" ,id:"introduction",placeholder:"施設詳細を入力", size: "5x5"  %>
    </div>

    <div class="form_btn">
    <%= f.label :price ,"料金" %>
    <div class="form_btn">
    <%= f.number_field :price ,class:"form-control" ,id:"price",placeholder:"料金を入力", size: 50 %>
    </div>


    <div class="form_btn">
    <%= f.label :address, "住所" %>
    <div class="form_btn">
    <%= f.text_field :address ,class:"form-control" ,id:"address",placeholder:"住所を入力",  size: 50 %>
    </div>


    <div class="iamge_form">
    <%= f.label :image, "施設画像" %>
    <%= f.file_field :image,class:"form-control" ,id:"image"%>

    <div class="form_btn">
    <%= f.submit "保存" ,class:"btn"%>
   
    </div>
<% end %>

app/views/rooms/own.html.erb
<section class="container RoomsContainer">
    <h2>登録済み一覧</h2>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>施設画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>宿泊料金</th>
          <th>作成日</th>
          <th>施設詳細</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.id %></td>
              <td>     
                <% if  room.image?%>
                  <%= image_tag room.image.url , class: "image", style: "width: 100px; height: 100px; object-fit:cover;"%>
                <% else %>
                  <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "image", style: "width: 100px; height: 100px; object-fit:cover;" %></p>
                <% end %>
              </td>
              <td><%= room.name %></td>
              <td><%= room.introduction %></td>
              <td><%= room.price %></td>
              <td><%= room.created_at.strftime("%Y/%m/%d")  %></td>
              <td><%= link_to "詳細" , room_path(room) %></td>
              <td><%= link_to "編集" , edit_room_path(room) %></td>
              <td><%= button_to "削除" , room_path(room), method: :delete , data: { confirm: "本当に削除しますか？" }%></td>
              </tr>
              <% end %>
              </tbody>
            </table>        
         

app/views/rooms/show.html.erb
<div class="container">
<%= flash[:danger] %> 
<%= render "shared/error", obj: @reservation %>

  <%= link_to "← 戻る",:back ,class:"room_back"%>
</div>


<div class="RoomForm">
 <% if  @room.image?%>
<%= image_tag @room.image.url ,class:"image", style: "width: 100px; height: 100px; object-fit:cover;"%>
<% else %>
  <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png',class: "image", style: "width: 100px; height: 100px; object-fit:cover;" %></p>
 <% end %>

<div class="RoomFormBody">

    <div class="RoomFormBody">
        <p class="RoomDetails__name"><%= @room.name %></p>
        <p class="RoomDetails__price"><%= @room.price %></p>
  
        <p class="RoomDetails__address"><%= @room.address %></p>
        <p class="RoomDetails__content"><%= @room.introduction %></p>
    </div> 

    <div class="ReservationForm">
 
    <%= form_with model:@reservation, url:confirm_reservation_path , local: true do |f| %>
      <%= f.hidden_field :room_id, value: @room.id %>

  <div class="ReservationForm__input-container">  
      <div class="ReservationForm__input">
        <%= f.label :check_in, "チェックイン" %>
      <div class="ReservationForm__input-date">
        <%= f.date_field :check_in  %>
      </div>
  </div>    
      <div class="ReservationForm__input">
        <%= f.label :check_out,"チェックイン"  %>
      <div class="ReservationForm__input-date">
        <%= f.date_field :check_out%>
      </div>
  </div>      
  <div class="ReservationForm__input-container--input--count_people">
      <div class="ReservationForm__input--count_people">
        <%= f.label :count_people, "人数" %>
        <%= f.number_field :count_people, min:1, placeholder:"0"%>
      </div>
 </div>  
 </div>

       <% if user_signed_in? %>
       <%= f.hidden_field :user_id, value: current_user.id %>
       <%= f.submit:予約する ,class:"ReservationForm_btn" %>
       <% else %>
       <%= link_to "ログイン", new_user_session_path, type: "button",class:"btn ReservationForm_btn" %>
   <%end%>



      </div>
      <% end %>