config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get 'homes/index'
  get 'users/new'
  devise_for :users, controllers: { registrations: 'users/registrations' }
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#index'
   get 'users/show'
   get 'users/edit'
   

  resources :users do
  end
   
  resources :rooms do
    member do
      get 'own'
    end
  end

  resources :reservations do
    member do
      post 'confirm'
      get 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :check_in,:check_out,:count_people, presence: true
 
  validate :start_finish_check
  validate :date_before_start
 
  def days
    days = (check_out - check_in).to_i
  end


  def total_price
    total_price = (days * count_people * room.price)
  end

 
  def date_before_start
    return if check_in.blank?
    errors.add(:check_in, "は今日以降のものを選択してください") if check_in < Date.today
  end
end
  def start_finish_check
    unless check_in.nil? || check_out.nil?
      errors.add(:check_out, "はチェックイン日より遅い日程を選択してください") if check_in >= check_out
    end
  end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations, dependent: :destroy

    validates :name,:introduction,:address, presence: true
    validates :price , numericality: { greater_than_or_equal_to: 1 }
  

    mount_uploader :image, ImageUploader
  

    def self.ransackable_attributes(auth_object = nil)
      ["address", "name","introduction"]
  end

  #よくわからないけど必要
  def self.ransackable_associations(auth_object = nil)
      ["user"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, presence: true, length: {maximum: 50}
      
         has_many :rooms
         has_many :reservations

         mount_uploader :icon, IconUploader
        end
     

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# ログイン済ユーザーのみにアクセスを許可する

before_action :configure_permitted_parameters, if: :devise_controller?
   

    protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    
  end
end
   
private
def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @user = current_user
  end

   def show
   @user = current_user
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def hello
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations =current_user.reservations
    @user = current_user
  end
 

  def confirm
    @user = current_user
    @reservation = Reservation.new(reservation_params)  #新しいreservationインスタンスにformからのパラメーターを入れる
    @room = Room.find(params[:reservation][:room_id])   #roomの情報をroom_idを使って得る
    if @reservation.invalid?
      flash[:danger] = @reservation.errors.full_messages
			redirect_to room_path(@room.id)
		else
    @user_id = current_user.id
    @days = (@reservation.check_out - @reservation.check_in).to_i 
    @total_price = (@days * @room.price * @reservation.count_people   ) 
  end
end

  def create
    @user = current_user
    @room = Room.find(params[:reservation][:room_id])
    @user = User.find_by(params[:reservation][:room_id])
    @reservation = Reservation.new(params.require(:reservation).permit(:check_in, :check_out, :count_people, :user_id, :room_id ,:created_at , :updated_at))

    if @reservation.save
      flash[:notice] = "予約に成功しました"
      redirect_to reservations_path (@reservation)
    else
      flash.now[:alert] = "予約に失敗しました"
      render "rooms/show"
    end
  end
  
    def show
    end
  
    def edit
    end
  
    def update
    end
  
    def destroy
      @reservation = Reservation.find(params[:id])
      @reservation.destroy
      flash[:notice] = "施設の予約を削除しました"
      redirect_to reservations_path
    end


  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :count_people , :user_id, :room_id , :created_at , :updated_at)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @user = current_user
  end

  def new
    @room = Room.new
    @user = current_user
   end

   def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id 
      if @room.save
        flash[:notice] = "新規登録しました"
        redirect_to @room
      else
        flash.now[:alert] = "登録に失敗しました"
        render "new"
      end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end


  def edit
    @room = Room.find(params[:id])
    @user = current_user
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "宿泊施設を更新しました"
      redirect_to @room
    else
      flash.now[:alert] = "宿泊施設の更新に失敗しました"
      render :edit , status: :unprocessable_entity
    end
  end

  def destroy
    @user = current_user
    @room = Room.find(params[:id])
    @room.destroy
      flash[:notice] = "ユーザーを削除しました"
      redirect_back(fallback_location: root_path)
  end

  def own
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end



  private
    def room_params
      params.require(:room).permit(
        :image,
        :name,
        :introduction,
        :price,
        :address,
        :user_id,
      )
    end

end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < ApplicationController

    def show

    end
  
    def edit
  
    end
  end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :sign_in_required, only: [:show ,:own ,:update]

  def index
    @users = User.all
    @rooms = Room.all
  end


  def new
    @user = User.new
  end

  
  def show
    @user = current_user

  end

  def edit
    @user = User.find(current_user.id)
  end


  def update
    @user = User.find(params[:id])
    if current_user.update(params.require(:user).permit(:icon, :name,:profile))
      flash[:notice] = "ユーザーIDが「#{@user.id}」の情報を更新しました"
      redirect_to users_show_path
    else
      flash.now[:alert] = "登録に失敗しました"
      render "edit"
    end
  end
end


private
    def user_params
      params.require(:user).permit(
        :icon,
        :name,
        :profile,
      )
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users/accounts_helper.rb
module Users::AccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <header>
    <nav class ="navbar Navbar">
       <div class="container-fluid">
         <a href="/"><img class="Navbar__logo" alt="サイトロゴ" src="https://rails-02-sample.herokuapp.com/assets/common/logo.png"></a>
     <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
         <a class="navbar-item"></a>
      <% if user_signed_in? %> 
       <% if @user.icon? %>
         <%= image_tag @user.icon.url, class: "icon", style: "border-radius: 30%; width: 50px; height: 50px; object-fit:cover;"%>
       <% else %>
         <p><%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png',class: "icon", style: "border-radius: 30%; width: 50px; height: 50px; object-fit:cover;" %></p>
      </div>
      <% end %>
      <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user.name %>
        </button>
        </button>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
        <li><%= link_to "アカウント", users_show_path(current_user) ,class: "dropdown-item"%></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "dropdown-item"%></li>
        <li><%= link_to "施設登録", new_room_path,class: "dropdown-item"%></li>
        <li><%= link_to "登録済み施設", own_room_path(current_user),class: "dropdown-item"%></li>
        <li><%= link_to "予約一覧", reservations_path,class: "dropdown-item"%></li>
        </ul>
    </div>
    <% else %>
      <!-- ユーザーがログインしていなかった時の処理 -->
      <h2> 現在ログインしていません </h2>
      <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
    <% end %>           
</div>
</div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<hr />
<%= yield %>
</body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></li>
        </ul>
    <% end %>
<% end %>